# Generated by Django 5.0.2 on 2024-03-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pages', models.IntegerField()),
                ('rating', models.CharField(choices=[('1.0', 1.0), ('1.5', 1.5), ('2.0', 2.0), ('2.5', 2.5), ('3.0', 3.0), ('3.5', 3.5), ('4.0', 4.0), ('4.5', 4.5), ('5.0', 5.0)], max_length=10)),
                ('published_date', models.DateField()),
                ('complete', models.BooleanField()),
                ('author', models.ManyToManyField(to='main.author')),
                ('genre', models.ManyToManyField(to='main.genre')),
                ('publisher', models.ManyToManyField(to='main.publisher')),
            ],
        ),
    ]
